CREATE TABLE IF NOT EXISTS PERSON (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRSTNAME VARCHAR(255),
	LASTNAME VARCHAR(255),
	MAIL VARCHAR(255),
	ADDRESS_ID BIGINT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ADDRESS (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STREET VARCHAR(255),
	CITY VARCHAR(255),
	ZIPCODE VARCHAR(255),
	PRIMARY KEY (ID)
);
